server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VHOST}
  web:
    error:
      include-stacktrace: never
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

pagbank:
  api:
    url: ${PAGBANK_API_URL}
    token: ${PAGBANK_API_TOKEN}
    payUrl: ${PAGBANK_API_PAY_URL}

gateway:
  config:
    notification-webhook-urls: ${GATEWAY_CONFIG_NOTIFICATION_WEBHOOK_URLS}
    payment-notification-urls: ${GATEWAY_CONFIG_PAYMENT_NOTIFICATION_URLS}
    payment-method: ${GATEWAY_CONFIG_PAYMENT_METHOD}
    soft-descriptor: ${GATEWAY_CONFIG_SOFT_DESCRIPTOR}
    return-url: ${GATEWAY_CONFIG_RETURN_URL}
    redirect-url: ${GATEWAY_CONFIG_REDIRECT_URL}
    customer-modifiable: ${GATEWAY_CONFIG_CUSTOMER_MODIFIABLE}

event:
  urls: ${EVENT_URLS}

payment:
  webhook:
    secret: ${PAYMENT_WEBHOOK_SECRET}

logging:
  level:
    root: warn
    com.csf: info

# MySQL connection for production profile
# Make sure to set MYSQL_HOST, MYSQL_PORT, MYSQL_DATABASE, MYSQL_USER, and MYSQL_PASSWORD in your environment.
# Add additional production settings as needed (e.g., logging, actuator, etc.)

